package cn.com.yves.module.persist.rdb.mybatis.client;

import java.util.List;

import cn.com.yves.module.bo.filter.UserFilter;
import cn.com.yves.module.persist.rdb.mybatis.model.UserModel;

public interface UserModelMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     * 
     * @mbggenerated Mon Sep 04 18:20:58 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     * 
     * @mbggenerated Mon Sep 04 18:20:58 CST 2017
     */
    int insert(UserModel record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     * 
     * @mbggenerated Mon Sep 04 18:20:58 CST 2017
     */
    int insertSelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     * 
     * @mbggenerated Mon Sep 04 18:20:58 CST 2017
     */
    UserModel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     * 
     * @mbggenerated Mon Sep 04 18:20:58 CST 2017
     */
    int updateByPrimaryKeySelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     * 
     * @mbggenerated Mon Sep 04 18:20:58 CST 2017
     */
    int updateByPrimaryKey(UserModel record);

    List<UserModel> listAll();

    List<UserModel> listByFilter(UserFilter filter);

}